app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(255))
    first_name = db.Column(db.String(255))
    last_name = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    music_path= db.Column(db.String())

    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SelectField,TextAreaField,SubmitField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask_sqlalchemy import SQLAlchemy
from flask import Flask
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from config import config_options
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES,AUDIO
from werkzeug.utils import secure_filename
from werkzeug.datastructures import FileStorage


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


boostrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
music= UploadSet('music',AUDIO)
mail = Mail()

def create_app(config_name):
    #Initializing application
    app = Flask(__name__)
    
    # Create the app configuration
    app.config.from_object(config_options[config_name])

    #Initializing Flask Extensions
    mail.init_app(app)
    boostrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    
    # configure UploadSet
    configure_uploads(app,photos)
    configure_uploads(app,music)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/auth')

    return app 

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, error

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..models import User
from .forms import UpdateProfile
from .. import db,photos,music
from flask_login import login_user, login_required, logout_user, current_user
from flask_mail import Message
from .. import mail
from ..requests import get_quotes

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    title = 'Home - Think|Space'
    # Getting the quotes
    quotes = get_quotes()
    print(quotes)
    return render_template('index.html',title=title,quotes=quotes)
    

@main.route('/home')
@login_required
def home():

    title = 'Home - Think|Space'
    
    return render_template('home.html', title=title)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user=user)
    
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html', form=form)
    
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))


@main.route('/user/<uname>/upload_music', methods=['POST'])
@login_required
def upload_music(uname):
    user = User.query.filter_by(username = uname).first()
    if 'music' in request.files:
        filename = music.save(request.files['music'])
        path = f'music/{filename}'
        user.music_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}
{% block styles %}
{{ super()}}
<!-- styles links -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" />
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}" />

{% endblock %}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/home.html
{% include 'base.html'%}
{% block styles%}
<link rel="stylesheet" bref="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block content%}
<section class="container text-center">
    <div class="parent">
        <div class="left">
            <article>
                <h3>Drown</h3>
                <img class="img-thumbnail" src="../static/photos/kovic.jpeg" alt="">
                <br>
                <audio controls>
                    <source
                        src="../static/music/Kovic x Hight _ Drown (Remix) _ feat. Dancer Josh Killacky _ Official.mp3">
                </audio>
                <p class="textma text-center"><em>By: Kovic x Hight</em></p>
            </article>
        </div>
        <div class="right">
            <article>
                <h3>Superman</h3>
                <img class="img-thumbnail" src="../static/photos/superman.jpeg" alt="">
                <br>
                <audio controls>
                    <source src="../static/music/Tarrus Riley Superman [Xsongspk.me].mp3">
                </audio>
                <p class="textmat text-center"><em>By: Tarrus Riley</em></p>
            </article>
        </div>
    </div>
    <br>
    <div class="parent">
        <div class="left">
            <article>
                <h3>10000 hours</h3>
                <img class="img-thumbnail" src="../static/photos/1000hrs.jpeg" alt="">
                <br>
                <audio controls>
                    <source src="../static/music/Dan + Shay, Justin Bieber - 10,000 Hours 🎵.mp3">
                </audio>
                <p class="textma text-center"><em>By: Dan & Shay</em></p>

            </article>
        </div>
        <div class="right">
            <article>
                <h3>Life is Good</h3>

                <img class="img-thumbnail" src="../static/photos/lifegood.jpeg" alt="">
                <br>
                <audio controls>
                    <source src="../static/music/Future - Life Is Good ft. Drake.mp3">
                </audio>
                <p class="textmat text-center"><em>By: Future ft Drake </em></p>
            </article>
        </div>
    </div>
    <br>
    <div class="parent">
        <div class="left">
            <article>
                <h3>Intentions</h3>
                <img class="img-thumbnail" src="../static/photos/intentions.jpeg" alt="">
                <br>
                <audio controls>
                    <source src="../static/music/Justin Bieber - Intentions ft. Quavo (Official Video).mp3">
                </audio>
                <p class="textma text-center"><em>By: Justin Beiber ft Quavo</em></p>
            </article>
        </div>
        <div class="right">
            <article>
                <h3>No Time to Die</h3>
                <img class="img-thumbnail" src="../static/photos/billie.jpeg" alt="">
                <br>
                <audio controls>
                    <source src="../static/music/Billie Eilish - No Time To Die (Audio).mp3">
                </audio>
                <p class="textmat text-center"><em>By: Billie Ellish</em></p>
            </article>
        </div>
    </div>
</section>

{% endblock %}

app/templates/index.html
{% include 'base.html' %}
<!-- Styles block -->

{% block styles%}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}

<!--Content block-->
{% block content%}
<div class="container text-center">
    <section class="se-container">
        <div class="se-slope">
            <article class="se-content">
                <h3>JAMZ 4 LIFE</h3>

            </article>
        </div>
        <div class="se-slope">
            <article class="se-content">
                <h3 class="text-center">
                    Quote & Beat
                </h3>
                <p class="container"><i class="fa fa-quote-left" style="font-size:24px"></i>
                    {{quotes.quote}}
                    <i class="fa fa-quote-right" style="font-size:24px"></i></p>
                <p class="textma text-center"><em>By: ~{{quotes.author}}~</em></p>
            </article>
        </div>
        <div class="se-slope">
            <article class="se-content">
                <h3>Get your Beat</h3>
                <p>
                <div>
                    {% if current_user.is_authenticated%}
                    <a id=" start" class="btn btn-danger text-center" href="{{url_for('main.home')}}"><span
                            class="view">View Music</span></a>
                    {% else %}
                    <a id="start" class="btn btn-danger text-center" href="{{url_for('auth.login')}}"><span
                            class="view">Sign
                            In</span>
                    </a>
                </div>
                {% endif %}</p>
            </article>
        </div>
    </section>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar " style="background-color: #9a1750;" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> JAMZ 4 LIFE </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/"><i class="fa fa-fw fa-home"
                            style="font-size:24px"></i> Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li class="nav-item"><a class="nav-link" href="/home"><i class="fa fa-headphones"
                            style="font-size:24px"></i> Music</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}

                <li style="color: white; padding: 15px;">
                    <i class="fa fa-fw fa-user" style="font-size:24px"></i>
                    {{current_user.username}}
                </li>
                <li>
                    <a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a>
                </li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>

app/templates/profile/profile.html
{% include 'base.html'%}

{% block content %}
<div class="container">
  <section class="se-container">
    <!-- displaying  Username-->
    <div class="se-slope text-center">
      <article class="se-content">
        <h3 class="text-center">
          Hey {{user.username| capitalize}}
        </h3>
        <hr>
        {% if user.profile_pic_path %}
        <img src="{{url_for('static',filename=user.profile_pic_path)}}" class="rounded-circle card-image-top img-fluid"
          alt="" class="img-thumbnail" style="width: 150px;height: 150px;">
        {%else%}
        <h4 class="textma"> kindly upload a profile picture:</h4>
        {% endif %}</p>
        <p class="textma text-center"><em>{% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
          </em></p>
      </article>
    </div>
    <div class="se-slope">
      <article class="se-content text-center">
        <!--Displaying user bio-->
        <h3 class="text-centre">Update Profile</h3>
        <br>
        {% if user == current_user %}
        <button><a class="bio" href="{{url_for('main.update_profile',uname=user.username)}}">Edit your profile
            here:</a></button>
        {% endif %}
        <br>
        <br>
        {% if user == current_user %}
        <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
          <input type="file" name="photo" class="form-control sub" required>
          <button type="submit">Submit</button>
        </form>
        {% endif %}

      </article>
    </div>
    <div class="se-slope">
      <article class="se-content text-center">
        {% if user == current_user %}

        <h3>Share Your Jam</h3>
        <h4>ALBUM COVER</h4>
        <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
          <input type="file" name="photo" class="form-control sub" required>
          <button type="submit">Submit</button>
        </form>
        <h4>MP3</h4>
        <form action="{{url_for('main.upload_music',uname=user.username)}}" method="POST" enctype="multipart/form-data">
          <div class="form-group">

            <div class="custom-music">
              <input type="file" class="custom-music-input" name="mp3" id="music">
              <label for="music" class="custom-music-label"></label>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Upload</button>
        </form>
        {% endif %}
      </article>
    </div>
  </section>
</div>
{% endblock %}

app/templates/profile/update.html
{% include 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}